<a href="https://colab.research.google.com/github/10KimJunGu/pythonadv/blob/main/1_%EB%84%98%ED%8C%8C%EC%9D%B4_%EB%AA%A8%EB%93%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Numpy

# 수학, 과학 계산용 패키지
# 성능 : 파이썬의 리스트보다 빠름
# 메모리 사이즈 : 파이썬의 리스트보다 적은 메모리를 사용
# 빌트인 함수 : 선형대수, 통계관련 여러 함수들을 내장


In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy

In [3]:
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [4]:
# 별칭(alias)지정
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [6]:
# 1-1. array(배열)

# 여러 값들의 그룹

In [7]:
arr = np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)  # numpy.ndarray = n dimension array

numpy.ndarray

In [10]:
list1 = [1,2,3,4]
list2 = [[1,2,3,4],[5,6,7,8]]

print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [11]:
# 리스트를 ndarray 생성하는 방법

arr1 = np.array(list1)
arr2 = np.array(list2)

In [14]:
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [15]:
arr1.shape # 데이터가 4개인(행이 4개) 1차원    # 차원

(4,)

In [16]:
arr2.shape # 행이 2개, 열이 4개(2행 4열)  2차원

(2, 4)

In [17]:
# 1-2. array의 data타입

# ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [18]:
list = [1, 3.14, 'python', '❤️', '1234', True]

In [19]:
list

[1, 3.14, 'python', '❤️', '1234', True]

In [20]:
list[3]

'❤️'

In [21]:
arr = np.array([1,2,3,4])

In [22]:
arr

array([1, 2, 3, 4])

In [23]:
arr = np.array([1,2,3, 3.14, 4])

In [24]:
arr

array([1.  , 2.  , 3.  , 3.14, 4.  ])

In [25]:
arr = np.array([1,2,3,3.14,'❤️', '1234'])

In [26]:
arr

array(['1', '2', '3', '3.14', '❤️', '1234'], dtype='<U32')

In [27]:
# int와 float 타입이 같이 존재하는 경우 int로 설정

arr = np.array([1,2,3, 3.14, 4], dtype=int)

In [28]:
arr

array([1, 2, 3, 3, 4])

In [29]:
# int와 str타입이 같이 존재하는 경우 int로 설정ㅍ

# arr = np.array([1,2,3,3.14,'❤️', '1234'], dtype=int)  # 에러발생

ValueError: ignored

In [30]:
# 1-3. 슬라이싱(slicing)

# 배열의 부분 선택


In [31]:
arr = np.array(['❤️', '😍','😁','😊','🤣'])
arr.shape

(5,)

In [32]:
print(arr[0])

❤️


In [33]:
print(arr[4])

🤣


In [34]:
print(arr[-1])

🤣


In [35]:
print(arr[0:3])  # 이상, 미만

['❤️' '😍' '😁']


In [36]:
print(arr[2:])

['😁' '😊' '🤣']


In [37]:
print(arr[:2])

['❤️' '😍']


In [39]:
arr2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [40]:
arr2d.shape

(3, 4)

In [41]:
arr2d[0,2]

3

In [43]:
arr2d[2,1]

10

In [44]:
# 0 행을 모두 가져오기

print(arr2d[0])
print(arr2d[0,])
print(arr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [45]:
# 1열을 모두 가져오기

print(arr2d[:,1])  # 행을 가져오는 방법은 여러가지이지만 열을 가져오는방법은 한가지 방법밖에 없다

[ 2  6 10]


In [46]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

In [ ]:
# 1-4. Fancy 인덱싱

# 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용


In [48]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [49]:
idx = [1, 3, 5]    # 인덱스 번호에 따라서 추출

In [50]:
arr[idx]

array([23,  7, 65])

In [51]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [52]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
# 1-5. Boolean 인덱싱

# 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [56]:
arr = np.array(['😜', '🎃', '😂', '😁', '😎'])

In [57]:
myValue = [True, False, True, False, True]

In [58]:
arr[myValue]

array(['😜', '😂', '😎'], dtype='<U1')

In [59]:
myValue = [True, False, True, False]
arr[myValue]  # IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4

IndexError: ignored

In [60]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [61]:
arr2d > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
arr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [63]:
arr2d[arr2d>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
arr2d[arr2d<7]

array([1, 2, 3, 4, 5, 6])

In [65]:
# 2. 행렬 연산



# 2-1. Matrix

# 행(row) + 열(column)
# 데이터분석 및 기계학습에서는 행렬을 제외하고 연산할 수 없음


In [66]:
# 2-2. 덧셈 연산

# shpae가 같아야 함
# 같은 position끼리 연산

In [68]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[4, 5],
              [2, 3]])

In [69]:
a + b # ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

ValueError: ignored

In [ ]:
# 2-3. 뺄셈 연산

# shpae가 같아야 함
# 같은 position끼리 연산

In [70]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [71]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [72]:
# 2-4. 곱셈 연산

# shpae가 같아야 함
# 같은 position끼리 연산

In [73]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [74]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [75]:
# 2-5. dot product

# 맞닿는 shape가 같아야 함

In [76]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [77]:
a.shape, b.shape

((3, 3), (3, 2))

In [78]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [79]:
(1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6)
(1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6)
(2*1 + 3*3 + 4*5), (2*2 + 3*4 + 4*6)

(31, 40)

In [80]:
# 2-6. arange

# 순차적인 값을 생성할 때 사용

In [81]:
arr = np.arange(1, 11) # 1부터 11미만

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr = np.arange(start=1, stop=11)

In [84]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr = np.arange(start=1, stop=11, step=2)

In [86]:
arr

array([1, 3, 5, 7, 9])

In [87]:
arr = range(1, 11) # 파이썬 표준 함수

In [88]:
arr

range(1, 11)

In [89]:
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [90]:
for i in range(1, 11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [91]:
arr = np.arange(1, 11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [92]:
# 2-7. 정렬(sort)

In [93]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [94]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [96]:
np.sort(arr) # 기본적으로 오른차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [97]:
np.sort(arr)[::-1] # 내림차순

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [98]:
arr # 값이 유지되지 않기 때문에 변수에 저장해야 함

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [99]:
result = np.sort(arr)

In [100]:
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [101]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [102]:
arr2d = np.array([[11, 10, 12, 9],
                 [3, 1, 4, 2],
                 [5, 6, 7, 8]])

In [103]:
arr2d.shape

(3, 4)

In [104]:
# 행 정렬
np.sort(arr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [105]:
# 열 정렬
np.sort(arr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [106]:
# 마지막 방향
np.sort(arr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [107]:
# 2-8. 숫자의 단일 연산

In [108]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[3, 3, 3],
              [3, 3, 3]])

In [109]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [110]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [111]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [112]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [113]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])